apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-node
spec:
  selector:
    app.kubernetes.io/name: openfiat-node
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: p2p
      port: {{ .Values.node.service.peerPort }}
      protocol: UDP
    - name: http
      port: {{ .Values.node.service.httpPort }}
