apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-node
spec:
  selector:
    app.kubernetes.io/name: openfiat-node
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: p2p
      port: {{ .Values.node.service.peerPort }}
    - name: rpc
      port: {{ .Values.node.service.rpcPort }}
    - name: metrics
      port: {{ .Values.node.service.metricsPort }}
